# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "congo"
darkMode = "true"
description = "Disciple of Experience"


[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = false

[article]
  showDate = true
  dateFormat = "2 January 2006"
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editURL = "https://github.com/benjamin421/thebenjamin/tree/main/content/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  showTableOfContents = true
  showReadingTime = true

[list]
  showBreadcrumbs = false
  showSummary = false
  groupByYear = true
 

[taxonomy]
  showTermCount = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]
